[package]
name = "auth-service-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum-core = "0.5.2"
chrono = "0.4.42"
email_address = "0.2.9"
http = "1.3.1"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
