[package]
name = "proxy-service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
http = "1.3.1"
pingora = { version = "0.6.0", features = ["proxy"] }

[features]
default = ["server"]
server = []
dev = []
